// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jqjmrpefwynolsnkfpxv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Impxam1ycGVmd3lub2xzbmtmcHh2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ4MjIzMjAsImV4cCI6MjA2MDM5ODMyMH0.UHpBI13k1_bxvqfRO500p3XYlHuwMSUy_VWW_aonkAU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);